[package]
name = "strmath"
description = "Do math with your strings."
keywords = ["string", "weird", "math", "zero-dependencies"]
authors = ["Rhelvetican <bionicvnb@gmail.com>"]
readme = "README.md"
license = "MIT"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/Rhelvetican/strmath"
homepage = "https://github.com/Rhelvetican/strmath"

[lib]
name = "strmath"
path = "src/lib.rs"
