[package]
name = "strmath"
description = "Do math with your strings."
keywords = ["string", "weird", "math", "zero-dependencies"]
authors = ["Rhelvetican <bionicvnb@gmail.com>"]
readme = "README.md"
license = "MIT"
version = "0.1.0"
edition = "2021"

