[package]
name = "strmath"
description = "Do math with your strings."
keywords = ["string", "strmath"]
authors = ["Rhelvetican <bionicvnb@gmail.com>"]
readme = "README.md"
license = "MIT"
version = "0.4.3"
edition = "2021"
repository = "https://github.com/Rhelvetican/strmath"
homepage = "https://github.com/Rhelvetican/strmath"

[lib]
name = "strmath"
path = "src/lib.rs"

[features]
add = []
sub = []
mul = []
div = []
rem = []
display = []

math = ["add", "sub", "mul", "div", "rem"]
full = ["math", "display"]
